# Generated by Django 3.2.9 on 2021-11-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211109_1905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custmer',
            new_name='Customer',
        ),
    ]
