# Generated by Django 3.2.9 on 2021-11-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_custmer_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Custmer',
        ),
    ]
