# Generated by Django 3.2.9 on 2021-11-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_customer_custmer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custmer',
            new_name='Customer',
        ),
    ]
